spring:

  application:
    name: tcg-data

  datasource:
    url: jdbc:postgresql://localhost:5432/tcg_data
    username: gato_tcg
    password: linosca321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  # Configuración de Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true